-- Generated by scripts/seed_matches.py
BEGIN TRANSACTION;
INSERT OR REPLACE INTO matches (id, fifa_match_no, stage, group_name, home_team, away_team, home_placeholder, away_placeholder, kickoff_at, venue) VALUES ('match_001', 1, 'GROUP', 'A', 'Mexico', 'South Africa', NULL, NULL, '2026-06-11T19:00:00Z', 'Estadio Azteca');
INSERT OR REPLACE INTO matches (id, fifa_match_no, stage, group_name, home_team, away_team, home_placeholder, away_placeholder, kickoff_at, venue) VALUES ('match_002', 2, 'GROUP', 'A', 'Canada', 'Qualifier A', NULL, NULL, '2026-06-12T00:00:00Z', 'BMO Field');
INSERT OR REPLACE INTO matches (id, fifa_match_no, stage, group_name, home_team, away_team, home_placeholder, away_placeholder, kickoff_at, venue) VALUES ('match_003', 3, 'GROUP', 'B', 'USA', 'Qualifier B', NULL, NULL, '2026-06-12T23:00:00Z', 'SoFi Stadium');
INSERT OR REPLACE INTO matches (id, fifa_match_no, stage, group_name, home_team, away_team, home_placeholder, away_placeholder, kickoff_at, venue) VALUES ('match_081', 81, 'ROUND_OF_32', NULL, NULL, NULL, 'Winner Group A', 'Runner-up Group B', '2026-06-28T19:00:00Z', 'TBD');
COMMIT;
