"""Convert a matches CSV into D1-compatible SQL inserts.

Usage:
    python scripts/seed_matches.py data/matches.csv db/seed_matches.sql
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

REQUIRED_COLUMNS = {
    "fifa_match_no",
    "stage",
    "kickoff_at",
}


def sql_quote(value: str | None) -> str:
    value = (value or "").strip()
    if not value:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def make_match_id(match_no: str) -> str:
    return f"match_{int(match_no):03d}"


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: python scripts/seed_matches.py data/matches.csv db/seed_matches.sql")
        return 2

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    if not input_path.exists():
        print(f"Input file not found: {input_path}")
        return 1

    with input_path.open(newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        missing = REQUIRED_COLUMNS - set(reader.fieldnames or [])
        if missing:
            print(f"Missing required columns: {', '.join(sorted(missing))}")
            return 1

        rows = list(reader)

    seen_match_numbers: set[int] = set()
    statements = ["-- Generated by scripts/seed_matches.py", "BEGIN TRANSACTION;"]

    for row in rows:
        match_no = int(row["fifa_match_no"])
        if match_no in seen_match_numbers:
            print(f"Duplicate fifa_match_no: {match_no}")
            return 1
        seen_match_numbers.add(match_no)

        statements.append(
            "INSERT OR REPLACE INTO matches "
            "(id, fifa_match_no, stage, group_name, home_team, away_team, home_placeholder, away_placeholder, kickoff_at, venue) "
            "VALUES ("
            f"{sql_quote(make_match_id(str(match_no)))}, "
            f"{match_no}, "
            f"{sql_quote(row.get('stage'))}, "
            f"{sql_quote(row.get('group_name'))}, "
            f"{sql_quote(row.get('home_team'))}, "
            f"{sql_quote(row.get('away_team'))}, "
            f"{sql_quote(row.get('home_placeholder'))}, "
            f"{sql_quote(row.get('away_placeholder'))}, "
            f"{sql_quote(row.get('kickoff_at'))}, "
            f"{sql_quote(row.get('venue'))}"
            ");"
        )

    statements.append("COMMIT;")
    output_path.write_text("\n".join(statements) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} matches to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
